<img src="Welcome_qbraid/slide1.png" height="600" width="700" />

<img src="Welcome_qbraid/slide2.png" height="600" width="700" />

<img src="Welcome_qbraid/slide3.png" height="600" width="700" />

<img src="Welcome_qbraid/slide4.png" height="600" width="700" />

In [2]:
import numpy as np

#orthogonal vector corresponding to possible outcomes
e0 = np.matrix([[1],[0],[0]])
e1 = np.matrix([[0],[1],[0]])
e2 = np.matrix([[0],[0],[1]])

#probabilities of possible outcomes
p0 = 0.05
p1 = 0.15
p2 = 0.8

#probability vector
p = p0 * e0 + p1 * e1 + p2 * e2



<img src="Welcome_qbraid/slide7.png" height="600" width="700" />

<img src="Welcome_qbraid/slide8.png" height="600" width="700" />

<img src="Welcome_qbraid/slide9.png" height="600" width="700" />

In [4]:
sig=[2,0,1]


#A matrix representation of the permutation
P_021=np.matrix(np.zeros((3,3)))
P_021[sig[0],0]=1
P_021[sig[1],1]=1
P_021[sig[2],2]=1

print(P_021)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [6]:
P_021@p

matrix([[0.15],
        [0.8 ],
        [0.05]])

<img src="Welcome_qbraid/slide12.png" height="600" width="700" />

<img src="Welcome_qbraid/slide13.png" height="600" width="700" />

In [8]:
w1=.5
w2=1-w1

(w1* P_021 + w2 * np.eye(3)) @ p

matrix([[0.1  ],
        [0.475],
        [0.425]])

<img src="Welcome_qbraid/slide14.png" height="600" width="700" />

<img src="Welcome_qbraid/slide15.png" height="600" width="700" />

<img src="Welcome_qbraid/slide16.png" height="600" width="700" />

<img src="Welcome_qbraid/slide17.png" height="600" width="700" />

<img src="Welcome_qbraid/slide19.png" height="600" width="700" />

I now invite the reader to reflect on the following aspects of probability theory before embarking on the extension to quantum.

* Meaning of measurement and the subsequent updating of probabilities
* Interpretation of the probability function
  * The probability function as  knowledge (epistemic)
  * The probability function as an actual thing (ontic)

<img src="Welcome_qbraid/slide18.png" height="600" width="700" />

<img src="Welcome_qbraid/slide20.png" height="600" width="700" />

In [11]:
# need to flatten the vector before using diag
# if you have numpy array (instead of a vector) 
# then np.diag will work directly

dm_p = np.diagflat(p)

print(dm_p)

[[0.05 0.   0.  ]
 [0.   0.15 0.  ]
 [0.   0.   0.8 ]]


<img src="Welcome_qbraid/slide21.png" height="600" width="700" />

In [16]:
# np matricies have attribute A.H for conjugate transpose
# alternatively one can use A.transpose().conjugate 

#print(e1.conjugate().transpose())
print(e1.H)

[[0 1 0]]


<img src="Welcome_qbraid/slide22.png" height="600" width="700" />

In [25]:
# use the @ for matrix multiplication in numpy

print("e1^dag e1 =",e1.H @ e1)
print(" ")
print("e0^dag e2 =", e0.H @ e2)
print(" ")
print("e2 e0^dag =")
print(e2 @ e0.H)
print(" ")
print("e0 e2^dag =")
print(e0 @ e2.H)


e1^dag e1 = [[1]]
 
e0^dag e2 = [[0]]
 
e2 e0^dag =
[[0 0 0]
 [0 0 0]
 [1 0 0]]
 
e0 e2^dag =
[[0 0 1]
 [0 0 0]
 [0 0 0]]


<img src="Welcome_qbraid/slide23.png" height="600" width="700" />

In [45]:
p_vec = [.25, .5, .15, .1]
L_p = np.diag(p_vec)

print(p_vec)
print(" ")
print(L_p)

[0.25, 0.5, 0.15, 0.1]
 
[[0.25 0.   0.   0.  ]
 [0.   0.5  0.   0.  ]
 [0.   0.   0.15 0.  ]
 [0.   0.   0.   0.1 ]]


<img src="Welcome_qbraid/slide26.png" height="600" width="700" />

In [59]:
# the unitary Fourier transform matrix
from scipy.linalg import dft
U=np.matrix(dft(3)/np.sqrt(3))
np.set_printoptions(suppress=True,precision=4)

#here dm stands for density matrix
dm = U @ dm_p @ U.H

#check that dm is a valid quantum state
print(dm)
print(" ")
print(np.trace(dm).real)
print(" ")
print(np.linalg.eig(dm)[0].real)
print(" ")
print(dm - dm.H)

[[ 0.3333+0.j     -0.1417-0.1876j -0.1417+0.1876j]
 [-0.1417+0.1876j  0.3333+0.j     -0.1417-0.1876j]
 [-0.1417-0.1876j -0.1417+0.1876j  0.3333+0.j    ]]
 
1.0
 
[0.8  0.05 0.15]
 
[[ 0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j -0.+0.j  0.+0.j]]


<img src="Welcome_qbraid/slide27.png" height="600" width="700" />

In [60]:
print(dm)
print(" ")
print(  (e0 @ e0.H) @ dm @ (e0 @ e0.H) 
      + (e1 @ e1.H) @ dm @ (e1 @ e1.H) 
      + (e2 @ e2.H) @ dm @ (e2 @ e2.H))

[[ 0.3333+0.j     -0.1417-0.1876j -0.1417+0.1876j]
 [-0.1417+0.1876j  0.3333+0.j     -0.1417-0.1876j]
 [-0.1417-0.1876j -0.1417+0.1876j  0.3333+0.j    ]]
 
[[0.3333+0.j 0.    +0.j 0.    +0.j]
 [0.    +0.j 0.3333+0.j 0.    +0.j]
 [0.    +0.j 0.    +0.j 0.3333+0.j]]


<img src="Welcome_qbraid/slide28.png" height="600" width="700" />

In [65]:
print(P_021 @ dm_p @ P_021.H)
print(" ")
print(P_021 @ p)


[[0.15 0.   0.  ]
 [0.   0.8  0.  ]
 [0.   0.   0.05]]
 
[[0.15]
 [0.8 ]
 [0.05]]


<img src="Welcome_qbraid/slide29.png" height="600" width="700" />

In [64]:
# the unitary Fourier transform matrix
from scipy.linalg import dft
U=np.matrix(dft(3)/np.sqrt(3))
np.set_printoptions(suppress=True,precision=4)

# An examples from earlier
print(U @ U.H)
print(" ")
print(P_021 @ P_021.H)

[[ 1.+0.j -0.+0.j  0.+0.j]
 [-0.-0.j  1.-0.j -0.+0.j]
 [ 0.-0.j -0.-0.j  1.-0.j]]
 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


<img src="Welcome_qbraid/slide30.png" height="600" width="700" />

In [73]:
w1=.5
w2=1-w1

dm_pf =  w1 * P_021 @ dm_p @ P_021.H\
       + w2 * np.eye(3) @ dm_p @ np.eye(3).T
pf    = (w1* P_021 @ p + w2 * np.eye(3) @ p ) 

print(dm_pf)
print(" ")
print(pf)

[[0.1   0.    0.   ]
 [0.    0.475 0.   ]
 [0.    0.    0.425]]
 
[[0.1  ]
 [0.475]
 [0.425]]


<img src="Welcome_qbraid/slide32.png" height="600" width="700" />

<img src="Welcome_qbraid/slide33.png" height="600" width="700" />

<img src="Welcome_qbraid/slide34.png" height="600" width="700" />

<img src="Welcome_qbraid/slide35.png" height="600" width="700" />

In [76]:
#random theta
q = np.random.rand() * 2 * np.pi
#random phi
f = np.random.rand() * 2 * np.pi

#the qubit wave function
psi = np.matrix( [[ np.cos(q) ] , [np.exp(-1j*f) * np.sin(q)] ] )

#quantum state (density matrix)
rho = np.matrix([[np.cos(q)**2 , .5 * np.exp(1j * f) * np.sin(2*q)],
       [.5 * np.exp(-1j * f) * np.sin(2*q), np.sin(q)**2]])

#standard quantum notation
ket0 = np.matrix( [[1],[0]])
ket1 = np.matrix( [[0],[1]])

#should be zero
print(psi @ psi.H - rho)
print(" ")
print(np.round(rho*10e4)/10e4 )
print(" ")
print((ket0 @ ket0.H) @ rho @ (ket0 @ ket0.H) 
      + (ket1 @ ket1.H) @ rho @ (ket1 @ ket1.H))

[[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]
 
[[0.6508+0.j     0.0437-0.4747j]
 [0.0437+0.4747j 0.3492+0.j    ]]
 
[[0.6508+0.j 0.    +0.j]
 [0.    +0.j 0.3492+0.j]]


<img src="Welcome_qbraid/slide36.png" height="600" width="700" />

<img src="Welcome_qbraid/slide37.png" height="600" width="700" />

<img src="Welcome_qbraid/slide38.png" height="600" width="700" />

<img src="Welcome_qbraid/slide39.png" height="600" width="700" />

<img src="Welcome_qbraid/slide40.png" height="600" width="700" />

<img src="Welcome_qbraid/slide41.png" height="600" width="700" />